import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { readFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const pkg = JSON.parse(readFileSync(join(repo, "package.json"), "utf8"));

const ACTOR_ID = "6hSpD3kd2s2IQ4VSs";
const SERVER_KEY = "mamba-youtube-channel-stats";
const PACKAGE_SLUG = "mcp-youtube-channel-transcript-extractor";
// Every tool the server registers, in registration order.
const TOOL_NAMES = ["get_youtube_channel_stats"];
// The tool that exposes every buyer input of the live actor.
const FULL_TOOL = "get_youtube_channel_stats";
// Smallest valid arguments for a tools/call against FULL_TOOL.
const CALL_ARGS = { company_domain: "hubspot.com" };

// The expected inputs come from the live actor, never from the tool. The
// fixture is a verbatim copy of the latest build's input schema, regenerated by
// scripts/sync-input-schema-fixture.mjs, so the test stays offline and still
// fails when the actor gains a field the tool does not expose.
const fixture = JSON.parse(
  readFileSync(join(here, "fixtures", "live-input-schema.json"), "utf8"),
);
const ACTOR_REQUIRED = fixture.required ?? [];
// source_tag is the landing page attribution tag the actor sets for itself, not
// something a caller supplies, and hidden fields are not buyer inputs.
const ACTOR_INPUTS = Object.entries(fixture.properties)
  .filter(([k, p]) => k !== "source_tag" && p.editor !== "hidden")
  .map(([k]) => k);

// Speak MCP over stdio to the built server. No APIFY_TOKEN unless asked, so a
// client sees capabilities before it has configured anything.
function rpc(messages, { env: extra = {}, waitFor = 2, timeoutMs = 30000 } = {}) {
  return new Promise((resolve, reject) => {
    const env = { ...process.env, ...extra };
    if (!extra.APIFY_TOKEN) delete env.APIFY_TOKEN;
    const child = spawn(process.execPath, [join(repo, "build", "index.js")], {
      stdio: ["pipe", "pipe", "pipe"],
      env,
    });
    let out = "";
    let err = "";
    const timer = setTimeout(() => {
      child.kill();
      reject(new Error(`timed out. stderr: ${err}`));
    }, timeoutMs);
    child.stdout.on("data", (chunk) => {
      out += chunk.toString();
      for (const line of out.split("\n")) {
        if (!line.trim()) continue;
        let msg;
        try {
          msg = JSON.parse(line);
        } catch {
          continue;
        }
        if (msg.id === waitFor) {
          clearTimeout(timer);
          child.kill();
          resolve(msg.result ?? msg.error);
        }
      }
    });
    child.stderr.on("data", (chunk) => {
      err += chunk.toString();
    });
    child.on("error", reject);
    const send = (m) => child.stdin.write(JSON.stringify(m) + "\n");
    send({
      jsonrpc: "2.0",
      id: 1,
      method: "initialize",
      params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "wrapper-test", version: "0.0.0" } },
    });
    send({ jsonrpc: "2.0", method: "notifications/initialized" });
    for (const m of messages) send(m);
  });
}

const listTools = () => rpc([{ jsonrpc: "2.0", id: 2, method: "tools/list", params: {} }]);
const fullTool = (tools) => tools.find((t) => t.name === FULL_TOOL);

function callTool(status) {
  const dir = mkdtempSync(join(tmpdir(), "wrapper-test-"));
  const logFile = join(dir, "fetch.log");
  const mock = pathToFileURL(join(here, "fixtures", "mock-fetch.mjs")).href;
  return rpc(
    [{ jsonrpc: "2.0", id: 2, method: "tools/call", params: { name: FULL_TOOL, arguments: CALL_ARGS } }],
    {
      env: {
        APIFY_TOKEN: "test-token",
        NODE_OPTIONS: `--import ${mock}`,
        MOCK_FETCH_LOG: logFile,
        MOCK_RUN_STATUS: status,
      },
    },
  ).then((result) => {
    let calls = [];
    try {
      calls = readFileSync(logFile, "utf8").trim().split("\n").map((l) => JSON.parse(l));
    } catch {
      calls = [];
    }
    return { result, calls };
  });
}

test("serves tools/list with no APIFY_TOKEN set", async () => {
  const result = await listTools();
  assert.deepEqual(result.tools.map((t) => t.name), TOOL_NAMES);
  for (const t of result.tools) assert.ok(t.description.length > 0);
});

test("tool schema exposes every live actor input", async () => {
  const result = await listTools();
  const props = Object.keys(fullTool(result.tools).inputSchema.properties).sort();
  assert.deepEqual(props, [...ACTOR_INPUTS].sort());
});

test("tool schema requires exactly what the live actor requires", async () => {
  const result = await listTools();
  const required = (fullTool(result.tools).inputSchema.required ?? []).slice().sort();
  assert.deepEqual(required, [...ACTOR_REQUIRED].sort());
});

test("every closed list input is constrained to the live actor values", async () => {
  // A string switch the actor types as "true"/"false" may be a boolean on the
  // tool (sent as a string); any other enum must match the actor's values exactly.
  const result = await listTools();
  const props = fullTool(result.tools).inputSchema.properties;
  const isBoolSwitch = (e) => e && e.length === 2 && e.includes("true") && e.includes("false");
  for (const name of ACTOR_INPUTS) {
    const live = fixture.properties[name];
    const liveEnum = live.enum ?? live.items?.enum;
    if (!liveEnum) continue;
    const tool = props[name];
    if (isBoolSwitch(liveEnum) && tool.type === "boolean") continue;
    const toolEnum = tool.enum ?? tool.items?.enum;
    assert.deepEqual([...(toolEnum ?? [])].sort(), [...liveEnum].sort(), `${name} enum drifted`);
  }
});

test("the fixture was read from this actor, not a sibling", () => {
  assert.equal(fixture._provenance.actorId, ACTOR_ID);
  assert.ok(ACTOR_INPUTS.length > 0);
});

test("source pins the immutable actor id and never calls run-sync", () => {
  const src = readFileSync(join(repo, "src", "index.ts"), "utf8");
  assert.ok(src.includes(`"${ACTOR_ID}"`), "actor id missing from source");
  assert.ok(!src.includes("run-sync-get-dataset-items?"), "run-sync endpoint still called");
});

test("starts the run, polls it, then reads the dataset", async () => {
  const { result, calls } = await callTool("SUCCEEDED");
  assert.ok(!result.isError, JSON.stringify(result));
  assert.match(calls[0].url, new RegExp(`/v2/acts/${ACTOR_ID}/runs\\?`));
  assert.equal(calls[0].method, "POST");
  assert.ok(calls.some((c) => c.url.includes("/v2/actor-runs/mockrun")));
  assert.ok(calls.at(-1).url.includes("/v2/datasets/mockds/items"));
  assert.deepEqual(JSON.parse(result.content[0].text), [{ row_status: "ok", mock: true }]);
});

test("a run that does not succeed is an error naming the run, never an empty result", async () => {
  const { result } = await callTool("FAILED");
  assert.equal(result.isError, true);
  assert.match(result.content[0].text, /mockrun/);
  assert.match(result.content[0].text, /FAILED/);
});

test("package identity matches the locked naming convention", () => {
  const mcp = JSON.parse(readFileSync(join(repo, ".mcp.json"), "utf8"));
  const key = Object.keys(mcp.mcpServers);
  assert.deepEqual(key, [SERVER_KEY]);
  assert.deepEqual(mcp.mcpServers[key[0]].args, ["-y", pkg.name]);
  assert.equal(pkg.name, `@mambalabsdev/${PACKAGE_SLUG}`);
  assert.equal(pkg.mcpName, `com.mambabuilt/${PACKAGE_SLUG}`);
});

test("the package ships only the declared allowlist", () => {
  assert.deepEqual(pkg.files, ["build", "README.md", "LICENSE", "SECURITY.md"]);
  assert.equal(pkg.bin[Object.keys(pkg.bin)[0]], "./build/index.js");
  assert.deepEqual(Object.keys(pkg.bin), [pkg.name.split("/")[1]]);
});
